name: Update README with Language Stats

on:
  push:
    branches:
      - main  # oder dein gewünschter Branch
  workflow_dispatch:  # Manuelles Triggern

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script to update README
        run: |
          python3 scripts/update_readme.py  # Dein Python-Skript zum Aktualisieren der README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token, um Berechtigungen zu haben

      - name: Commit changes to README
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with language stats"
          # Hier den richtigen Push-Befehl mit Token verwenden
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
