name: Update README with Language Stats

on:
  push:
    branches:
      - main  # Setze hier den Branch-Namen, auf dem der Workflow ausgeführt werden soll
  workflow_dispatch:  # Ermöglicht manuelle Ausführung

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script to update README
        run: |
          python3 scripts/update_readme.py  # Hier den Pfad zu deinem Skript anpassen

      - name: Commit changes to README
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with language stats"
          git push
