name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Täglich um Mitternacht
  workflow_dispatch:     # Ermöglicht manuelle Ausführung

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Installiere Python (oder andere Abhängigkeiten, falls benötigt)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Generiere Statistiken (z. B. Commit-Zeiten)
      - name: Generate Commit Stats
        run: |
          pip install requests
          python scripts/update_readme.py

      # Füge Änderungen in die README ein
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
